swapi_explorer/explorer_app/urls.py
from django.urls import path

from .views import FileView, IndexView, CountView


app_name = 'explorer_app'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('file/<str:filename>', FileView.as_view(), name='file'),
    path('file/<str:filename>/count', CountView.as_view(), name='count'),
]

swapi_explorer/swapi_explorer/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('explorer_app.urls')),
    path('admin/', admin.site.urls),
]

swapi_explorer/explorer_app/models.py
from django.db import models


class File(models.Model):
    name = models.CharField(max_length=40)
    creation_date = models.DateTimeField('creation date')

swapi_explorer/explorer_app/views.py
from ast import literal_eval
from datetime import datetime

from django.http import HttpRequest, HttpResponse
from django.shortcuts import redirect, render
from django.views import View
from django.views.generic import ListView

from .models import File
from .logic.etl_controller import ETLController


class IndexView(ListView):
    model = File
    context_object_name = 'file_list'
    queryset = File.objects.order_by('-creation_date')
    template_name = 'explorer_app/index.html'

    def post(self, request: HttpRequest) -> HttpResponse:
        if 'fetch' in request.POST:
            filename = ETLController.create_empty()
            File.objects.create(name=filename, creation_date=datetime.now())
            ETLController.fetch(filename)
        return redirect('explorer_app:index')


class FileView(View):
    template_name = 'explorer_app/file.html'

    def get(self, request: HttpRequest, filename: str) -> HttpResponse:
        return self._handle_request(request, filename, counter=11)

    def post(self, request: HttpRequest, filename: str) -> HttpResponse:
        counter = request.POST.get('load_more')
        if counter is not None:
            return self._handle_request(request, filename, counter=int(counter) + 10)

    def _handle_request(self, request: HttpRequest, filename: str, counter: int) -> HttpResponse:
        people_table = ETLController.load(filename)
        context = {
            'counter': counter,
            'filename': filename,
            'table_head': people_table[0],
            'table_body': people_table[1:counter],
        }
        return render(request, self.template_name, context=context)


class CountView(View):
    template_name = 'explorer_app/count.html'

    def get(self, request: HttpRequest, filename: str) -> HttpResponse:
        people_table = ETLController.load(filename)
        context = {
            'filename': filename,
            'buttons': {name: False for name in people_table[0]}
        }
        return render(request, self.template_name, context=context)

    def post(self, request: HttpRequest, filename: str) -> HttpResponse:
        buttons = literal_eval(request.POST['buttons'])
        buttons[request.POST['selected_button']] = not buttons[request.POST['selected_button']]
        context = {
            'filename': filename,
            'buttons': buttons,
        }
        count_by = tuple(name for name, is_highlighted in buttons.items() if is_highlighted)
        if count_by:
            count_table = ETLController.count(
                source=filename,
                by=count_by if not len(count_by) == 1 else count_by[0]
            )
            context = {
                **context,
                'table_head': count_table[0],
                'table_body': count_table[1:],
            }
        return render(request, self.template_name, context=context)

swapi_explorer/explorer_app/templates/explorer_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css"/>
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <section class="hero is-primary is-fullheight">
        <div class="hero-head">
            <nav class="navbar">
                <div class="container">
                    <div id="navbarMenu" class="navbar-menu">
                        <div class="navbar-item">
                            <div class="label has-text-white">
                                Star Wars Explorer
                            </div>
                        </div>
                        <a href="/" class="navbar-item">
                            Collections
                        </a>
                    </div>
                </div>
            </nav>
            <div class="container is-align-self-center">
               {% block content %}
               {% endblock %}
            </div>
        </div>

    </section>
</body>
</html>

swapi_explorer/explorer_app/templates/explorer_app/count.html
{% extends "explorer_app/base.html" %}

{% block title %} Value count {% endblock %}

{% block content %}

<div class="field">
    <div class="title">
        {{ filename }}
    </div>
    <div class="buttons">
        <form method="POST" action="{% url 'explorer_app:count' filename %}">
            {% csrf_token %}
            <input type="hidden" name="buttons" value="{{ buttons }}">
            {% for button_name, is_highlighted in buttons.items %}
                <button name="selected_button"
                        value="{{ button_name }}"
                        class="button {% if is_highlighted %} is-info {% endif %}">
                    {{ button_name }}
                </button>
            {% endfor %}
        </form>
    </div>
</div>

<div class="row">
    <table class="table">
        <thead>
            <tr>
                {% for field in table_head %}
                    <th scope="col">{{ field }}</th>
                {% endfor %}
            </tr>
        </thead>
        <tbody>
            {% for table_row in table_body %}
                <tr>
                    {% for table_elem in table_row %}
                        <td>
                            {{ table_elem }}
                        </td>
                    {% endfor %}
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>


{% endblock %}

swapi_explorer/explorer_app/templates/explorer_app/file.html
{% extends "explorer_app/base.html" %}

{% block title %} File {% endblock %}

{% block content %}

<div class="field">
    <div class="title">
        {{ filename }}
    </div>
    <p class="control">
        <a href="{% url 'explorer_app:count' filename %}">
            <button name="view_count" class="button is-info">View count</button>
        </a>
    </p>
</div>

<div class="row">
    <table class="table">
        <thead>
            <tr>
                {% for field in table_head %}
                    <th scope="col">{{ field }}</th>
                {% endfor %}
            </tr>
        </thead>
        <tbody>
            {% for table_row in table_body %}
                <tr>
                    {% for table_elem in table_row %}
                        <td>
                            {{ table_elem }}
                        </td>
                    {% endfor %}
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<div class="field">
    <form method="POST" action="{% url 'explorer_app:file' filename %}">
        {% csrf_token %}
        <p class="control">
            <button name="load_more" value="{{ counter }}" class="button is-info">Load more</button>
        </p>
    </form>
</div>

{% endblock %}

swapi_explorer/explorer_app/templates/explorer_app/index.html
{% extends "explorer_app/base.html" %}

{% block title %} Home {% endblock %}

{% block content %}

<div class="field">
    <div class="title">
        Collections
    </div>
    <form method="POST" action="{% url 'explorer_app:index' %}">
        {% csrf_token %}
        <p class="control">
            <button name="fetch" class="button is-info">Fetch</button>
        </p>
    </form>
</div>

<div class="row">
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Name</th>
                <th scope="col">Creation date</th>
            </tr>
        </thead>
        <tbody>
            {% for file in file_list %}
                <tr>
                    <td>
                        <div class="has-text-link">
                            <a href="{% url 'explorer_app:file' file.name %}">
                                {{ file.name }}
                            </a>
                        </div>
                    </td>
                    <td>
                        {{ file.creation_date }}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}